print("hello,world")
print("what is the mean of coders")
print("this is the hello world")
print("I am the new coders")
print('t ')
print(" hello world")
print("simple python language")
print('we write its single inverted comma')
print('we write its double inverted comma')